config_keys:
  dataset:
    name: set

  ood_dataset:
    name: oods

  network:
    name: net

  pipeline:
    name: pipeline

  evaluator:
    name: evaluator

  postprocessor:
    tta_epochs: epochs
    name: method
    postprocessor_args: param
  
