logger:
  __default__: warning
  __main__: 
  logger:
  configdict:
  load: 
  table:
  filters:
  scores:

load:
  result_directory: ./results

  ood_csv: ood.csv
  csv_index:
    dataset: ood
    epoch: epoch
    phase: phase
  parse_dates: [date]

  config_yml: config.yml

  flash: True

  index_fill_values:
    epoch: 0
    epochs: 0
    it: 0
    margin: 0.
    mu_: none
    phase: none
    gasless: False
    pad_ext: none
    score_path: none

args:
  aliases:
    logger.main: [--log, --debug:debug]
    logger.__default__: [--full-log]
    load.result_directory: [-r]
    no-load.flash: [--reload]
  
  exclude:
    - args
    - load.config_keys
    - table.index_dependencies
    - load.index_fill_values
    - load.csv_index

scores:
  plot: False
  max_plots: 3
  id_q: 0.1
  plots:
    - hist
