logger:
  __default__: warning
  __main__: 
  logger: 
  load: 
  tables:
  filters:  

results_directory: ./results

ood_csv: ood.csv
config_yml: config.yml

aliases:
  logger.__main__: [--log, --debug:debug]
  logger.__default__: --full-log
  results_directory: -r
  no-flash: --reload
  
