table:
  exp_index:
    - exp
    - job
    - date
    - workers
    - path
    - has_scores
  hidden_index:
    - epoch
    - oods

  show: []
  drop_unique: True
  show_dropped: True
  index_order: ['set', 'net', '...', 'ood', 'phase', 'epoch', 'date', 'job']
  list_values:
  
  index_dependencies:
    beta: [s_ood]
    epochs: [it]
    lr: [wd]

  columns:
    FPR@95: fpr
    AUROC: auc
    ACC: 
    AUPR_IN:
    AUPR_OUT:
    SCORES:
    ID_Q: id_q
    OOD_Q: ood_q
    ID_M: id
    OOD_M: ood
    OOD_STD: ood_std
    
  create_col:
    iter: \chunk * (1 + max(\id_pad, 0) + max(\ood_pad, 0) + \self_pad) * \epochs / \batch_size
  
