table:
  exp_index:
    - exp
    - job
    - date
    - workers
    - path
    - has_scores
  hide:
    - epoch
    - oods
    - preproc

  show: []
  drop_unique: True
  show_dropped: True
  index_order: [set, net, ..., ood, phase, epoch, date, job]
  list_values:
  float_format: '{:.1f}'

  max_length: 200
    
  index_dependencies:
    beta: [s_ood]
    lr: [wd]

  columns:
    FPR@95: fpr
    AUROC: auc
    ACC: 
    AUPR_IN:
    AUPR_OUT:
    SCORES:
    ID_Q: id_q
    OOD_Q: ood_q
    ID_MEAN: id
    ID_STD: id_std
    ID_SKEW: id_skew
    ID_MEDCOUPLE: id_medcouple
    ID_KURTOSIS: id_kurt
    ID_IQR: id_iqr
    OOD_MEAN: ood
    OOD_STD: ood_std
    OOD_SKEW: ood_skew
    OOD_MEDCOUPLE: ood_medcouple
    OOD_KURTOSIS: ood_kurt
    OOD_IQR: ood_iqr
    FISHER: fisher
    
  tex:
    filename: '' #/tmp/table.tex
    columns:
      FPR@95: 
      AUROC: AUC
      ACC: 
      AUPR_IN:
      AUPR_OUT:
      ID_Q: 
      OOD_Q:
      ID_M: 
      ID_STD: 
      ID_SKEW: id skew
      OOD_M: 
      OOD_STD: 
      OOD_SKEW:
    index:
      chunk:
        name: $N$
      grad:
        name: $\nabla$
        values:
          penultimate: pen
        ood_period:
          name: $T_{\text{OOD}}$
        mu_alt:
          name: $\mu_{\text{alt}}$
