table:
  hidden_index:
    - exp
    - job
    - date
    - oods
    - workers
    - epoch
    - path

  show: []
  drop_unique: True
  index_order: ['set', 'net', '...', 'ood', 'phase', 'epoch', 'date', 'job']

  index_dependencies:
    beta: [s_ood]
    epochs: [it]
    lr: [wd]

  create_col:
    iter: \chunk * (1 + max(\id_pad, 0) + max(\ood_pad, 0) + \self_pad) * \epochs / \batch_size
  
